export interface FaqEntry {
  id: string;
  category: string;
  keywords: string[]; // EN + ES keywords for bilingual matching
  question: string; // i18n key
  answer: string; // i18n key
  relatedIds?: string[];
}

export const faqDatabase: FaqEntry[] = [
  // ── Getting Started ──────────────────────────────────────────
  {
    id: 'what-is-mvga',
    category: 'getting-started',
    keywords: [
      'what',
      'mvga',
      'about',
      'qué',
      'es',
      'acerca',
      'que es',
      'what is',
      'app',
      'aplicación',
    ],
    question: 'help.faq1q',
    answer: 'help.faq1a',
    relatedIds: ['self-custody', 'fees'],
  },
  {
    id: 'create-wallet',
    category: 'getting-started',
    keywords: [
      'create',
      'wallet',
      'new',
      'account',
      'register',
      'sign up',
      'crear',
      'billetera',
      'nueva',
      'cuenta',
      'registrar',
    ],
    question: 'help.faq7q',
    answer: 'help.faq7a',
    relatedIds: ['backup-phrase', 'self-custody'],
  },
  {
    id: 'backup-phrase',
    category: 'getting-started',
    keywords: [
      'backup',
      'recovery',
      'phrase',
      'mnemonic',
      'seed',
      'words',
      '12',
      'twelve',
      'respaldo',
      'recuperación',
      'frase',
      'semilla',
      'palabras',
      'doce',
    ],
    question: 'help.faq8q',
    answer: 'help.faq8a',
    relatedIds: ['lost-password', 'self-custody'],
  },
  {
    id: 'biometrics',
    category: 'getting-started',
    keywords: [
      'biometric',
      'face',
      'fingerprint',
      'touch',
      'unlock',
      'biométrico',
      'facial',
      'huella',
      'desbloquear',
      'passkey',
    ],
    question: 'help.faq9q',
    answer: 'help.faq9a',
  },
  {
    id: 'profile',
    category: 'getting-started',
    keywords: [
      'profile',
      'name',
      'email',
      'username',
      'perfil',
      'nombre',
      'correo',
      'usuario',
      'citizen',
      'ciudadano',
    ],
    question: 'help.faq10q',
    answer: 'help.faq10a',
  },

  // ── Deposits ─────────────────────────────────────────────────
  {
    id: 'how-deposit',
    category: 'deposits',
    keywords: [
      'deposit',
      'add',
      'fund',
      'money',
      'depositar',
      'agregar',
      'fondear',
      'dinero',
      'how to deposit',
      'como depositar',
    ],
    question: 'help.faq11q',
    answer: 'help.faq11a',
    relatedIds: ['ves-onramp', 'paypal-deposit'],
  },
  {
    id: 'paypal-deposit',
    category: 'deposits',
    keywords: ['paypal', 'deposit', 'depositar'],
    question: 'help.faq12q',
    answer: 'help.faq12a',
    relatedIds: ['how-deposit'],
  },
  {
    id: 'ves-onramp',
    category: 'deposits',
    keywords: [
      'bolivar',
      'bolívar',
      'ves',
      'pago',
      'movil',
      'móvil',
      'venezuela',
      'bs',
      'onramp',
      'on-ramp',
      'local',
    ],
    question: 'help.faq13q',
    answer: 'help.faq13a',
    relatedIds: ['how-deposit', 'p2p-trading'],
  },
  {
    id: 'receive-crypto',
    category: 'deposits',
    keywords: [
      'receive',
      'remittance',
      'qr',
      'address',
      'recibir',
      'remesa',
      'dirección',
      'solana',
    ],
    question: 'help.faq2q',
    answer: 'help.faq2a',
  },

  // ── Sending ──────────────────────────────────────────────────
  {
    id: 'how-send',
    category: 'sending',
    keywords: ['send', 'transfer', 'enviar', 'transferir', 'pay', 'pagar', 'usdc', 'sol'],
    question: 'help.faq14q',
    answer: 'help.faq14a',
    relatedIds: ['qr-scan', 'batch-send'],
  },
  {
    id: 'qr-scan',
    category: 'sending',
    keywords: ['qr', 'scan', 'camera', 'escanear', 'cámara', 'solana pay'],
    question: 'help.faq15q',
    answer: 'help.faq15a',
  },
  {
    id: 'batch-send',
    category: 'sending',
    keywords: ['batch', 'multiple', 'multi', 'bulk', 'lote', 'múltiple', 'varios', 'many'],
    question: 'help.faq16q',
    answer: 'help.faq16a',
  },

  // ── P2P Trading ──────────────────────────────────────────────
  {
    id: 'p2p-trading',
    category: 'p2p',
    keywords: [
      'p2p',
      'peer to peer',
      'trade',
      'exchange',
      'buy',
      'sell',
      'intercambio',
      'comprar',
      'vender',
      'peer',
      'how p2p',
      'como p2p',
    ],
    question: 'help.faq4q',
    answer: 'help.faq4a',
    relatedIds: ['escrow', 'p2p-dispute'],
  },
  {
    id: 'escrow',
    category: 'p2p',
    keywords: [
      'escrow',
      'custody',
      'locked',
      'custodia',
      'bloqueado',
      'garantía',
      'safe',
      'seguro',
    ],
    question: 'help.faq17q',
    answer: 'help.faq17a',
    relatedIds: ['p2p-trading'],
  },
  {
    id: 'p2p-dispute',
    category: 'p2p',
    keywords: [
      'dispute',
      'problem',
      'scam',
      'fraud',
      'issue',
      'disputa',
      'problema',
      'estafa',
      'fraude',
      'reclamo',
    ],
    question: 'help.faq18q',
    answer: 'help.faq18a',
    relatedIds: ['escrow'],
  },
  {
    id: 'p2p-methods',
    category: 'p2p',
    keywords: [
      'zelle',
      'venmo',
      'paypal',
      'bank',
      'transfer',
      'binance',
      'pago',
      'movil',
      'payment',
      'method',
      'método',
      'pago',
    ],
    question: 'help.faq19q',
    answer: 'help.faq19a',
  },

  // ── Card ─────────────────────────────────────────────────────
  {
    id: 'card-get',
    category: 'card',
    keywords: [
      'card',
      'get card',
      'visa',
      'debit',
      'tarjeta',
      'débito',
      'virtual',
      'physical',
      'física',
      'obtener tarjeta',
    ],
    question: 'help.faq20q',
    answer: 'help.faq20a',
    relatedIds: ['kyc', 'apple-pay'],
  },
  {
    id: 'kyc',
    category: 'card',
    keywords: [
      'kyc',
      'verify',
      'identity',
      'id',
      'verification',
      'verificar',
      'identidad',
      'verificación',
      'persona',
    ],
    question: 'help.faq21q',
    answer: 'help.faq21a',
    relatedIds: ['card-get'],
  },
  {
    id: 'apple-pay',
    category: 'card',
    keywords: ['apple', 'google', 'pay', 'wallet', 'contactless', 'nfc', 'provisioning'],
    question: 'help.faq22q',
    answer: 'help.faq22a',
  },

  // ── Savings & Staking ────────────────────────────────────────
  {
    id: 'savings',
    category: 'savings',
    keywords: [
      'savings',
      'yield',
      'interest',
      'earn',
      'apy',
      'ahorros',
      'rendimiento',
      'interés',
      'ganar',
      'kamino',
    ],
    question: 'help.faq23q',
    answer: 'help.faq23a',
    relatedIds: ['staking', 'defi-risks'],
  },
  {
    id: 'staking',
    category: 'savings',
    keywords: ['stake', 'staking', 'lock', 'reward', 'mvga', 'token', 'bloquear', 'recompensa'],
    question: 'help.faq3q',
    answer: 'help.faq3a',
    relatedIds: ['savings'],
  },
  {
    id: 'defi-risks',
    category: 'savings',
    keywords: [
      'risk',
      'safe',
      'defi',
      'smart contract',
      'riesgo',
      'seguro',
      'contrato',
      'inteligente',
      'loss',
      'pérdida',
    ],
    question: 'help.faq24q',
    answer: 'help.faq24a',
    relatedIds: ['self-custody'],
  },

  // ── Cash Out ─────────────────────────────────────────────────
  {
    id: 'cashout-airtm',
    category: 'cashout',
    keywords: [
      'cash',
      'out',
      'withdraw',
      'airtm',
      'retiro',
      'retirar',
      'cobrar',
      'off-ramp',
      'offramp',
    ],
    question: 'help.faq25q',
    answer: 'help.faq25a',
    relatedIds: ['cashout-moneygram', 'cashout-giftcard'],
  },
  {
    id: 'cashout-moneygram',
    category: 'cashout',
    keywords: ['moneygram', 'cash', 'pickup', 'location', 'efectivo', 'sucursal', 'recoger'],
    question: 'help.faq26q',
    answer: 'help.faq26a',
  },
  {
    id: 'cashout-giftcard',
    category: 'cashout',
    keywords: [
      'gift',
      'gift card',
      'giftcard',
      'bitrefill',
      'netflix',
      'spotify',
      'amazon',
      'tarjeta de regalo',
      'regalo',
    ],
    question: 'help.faq27q',
    answer: 'help.faq27a',
  },

  // ── Security ─────────────────────────────────────────────────
  {
    id: 'self-custody',
    category: 'security',
    keywords: [
      'self',
      'custody',
      'custodial',
      'keys',
      'private',
      'own',
      'custodia',
      'llaves',
      'privada',
      'propias',
      'non-custodial',
    ],
    question: 'help.faq28q',
    answer: 'help.faq28a',
    relatedIds: ['backup-phrase', 'lost-password'],
  },
  {
    id: 'lost-password',
    category: 'security',
    keywords: [
      'lost',
      'forgot',
      'password',
      'recover',
      'reset',
      'perdí',
      'olvidé',
      'contraseña',
      'recuperar',
      'restablecer',
    ],
    question: 'help.faq29q',
    answer: 'help.faq29a',
    relatedIds: ['backup-phrase', 'self-custody'],
  },

  // ── Fees ─────────────────────────────────────────────────────
  {
    id: 'fees',
    category: 'fees',
    keywords: [
      'fee',
      'cost',
      'price',
      'commission',
      'tarifa',
      'costo',
      'precio',
      'comisión',
      'free',
      'gratis',
      'charge',
      'cobro',
    ],
    question: 'help.faq6q',
    answer: 'help.faq6a',
  },
  {
    id: 'topup',
    category: 'deposits',
    keywords: [
      'topup',
      'top-up',
      'phone',
      'airtime',
      'mobile',
      'recharge',
      'recarga',
      'teléfono',
      'celular',
      'saldo',
    ],
    question: 'help.faq30q',
    answer: 'help.faq30a',
  },
];
